version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:8-jdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: ls -l
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
          
      - run:
          name: Config
          command: |
            mvn -version
            gradle -version
            
      - run:
          name: Config
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt c show
            
      - run:
          name: Gradle install
          command: |
            ./jfrog rt gradle 'clean install artifactoryPublish' gradle.conf  --build-name=circleci-gradle-artifactory --build-number=$CIRCLE_BUILD_NUM

