version: 2.1
jobs:
  build:
    docker: 
      - image: maven:3.5.4-jdk-8-alpine # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: ls -l
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
          
      - run:
          name: Config
          command: |
            mvn -version
